version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda

  create_conda_env: &create_conda_env
    run:
      name: create conda env
      command: conda env create -n kipoi-dev python=3.6

  install_kipoi_utils: &install_kipoi_utils
    run:
      name: Install kipoi_utils
      command: |
        source activate kipoi-dev
        pip install '.[develop]'
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        mkdir test-reports
        source activate kipoi-dev
        py.test --cov=kipoi_utils/ tests/ -n 1 --no-cov-on-fail --junitxml=test-reports/junit.xml
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: |
        source activate kipoi-dev
        coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports


jobs:

  test-py36:
    docker:
      - image: kipoi/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *create_conda_env
      - *install_kipoi_utils
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts
workflows:
  version: 2

  test:
    jobs:
      - test-py36
      # - build-deploy-docs:
      #     requires:
      #       - test-py36
      #       - test-py27
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - test_deployment_script
