site_name: Kipoi-veff

# ------- readthedocs ---------
theme:
 name: readthedocs
 custom_dir: theme_dir
extra_css: [css/extra.css]
# --------------------------
docs_dir: sources
repo_url: http://github.com/kipoi/kipoi-veff
site_url: http://kipoi.org/docs/veff/
edit_uri: edit/master/docs/templates/
site_description: 'Documentation of Kipoi-veff, variant effect prediction plugin for Kipoi.'

dev_addr: '0.0.0.0:8000'

google_analytics: ["UA-115025493-1", "kipoi.org"]

pages:
- Home: index.md
- Overview: overview.md
- Using: using.md
- Tutorials: # compiled from ipynb. Listed in ipynb_pages.txt
  - Simple: tutorials/variant_effect_prediction_simple.md
  - Advanced: tutorials/variant_effect_prediction.md
  - Mutation map: tutorials/mutation_map.md
- Api:
  - score_variants: api/score_variants.md
  - predict_snvs: api/predict_snvs.md
  - Available scores: api/scores.md
  - MutationMap: api/MutationMap.md
  - MutationMapPlotter: api/MutationMapPlotter.md
  - KipoiVCFParser: api/KipoiVCFParser.md
